- name: Получить информацию о контейнере mysql_master
  community.docker.docker_container_info:
    name: mysql_master
  register: master_container_info
  become: yes

- name: Получить информацию о контейнере mysql_replica
  community.docker.docker_container_info:
    name: mysql_replica
  register: replica_container_info
  become: yes

- name: Вывести статус контейнеров (для отладки)
  debug:
    msg: |
      Статус контейнера mysql_master: {{ master_container_info.container.state.status | default('не найден или не запущен') }}
      Статус контейнера mysql_replica: {{ replica_container_info.container.state.status | default('не найден или не запущен') }}

- name: Ожидаем доступности порта MySQL на мастере (3306)
  ansible.builtin.wait_for:
    host: 127.0.0.1
    port: 3306
    delay: 10
    timeout: 60
    state: started

- name: Настраиваем репликацию на реплике MySQL
  community.mysql.mysql_replication:
    login_host: 127.0.0.1
    login_user: root
    login_password: "{{ mysql_root_password }}"
    primary_host: mysql_master
    primary_user: replicator
    primary_password: "{{ replication_password }}"
    primary_use_gtid: true
    mode: startreplica
  register: replication_setup_result
  become: yes

- name: Проверяем статус настройки репликации
  debug:
    var: replication_setup_result

- name: Проверяем статус репликации MySQL
  community.mysql.mysql_query:
    login_host: 127.0.0.1  # или IP контейнера mysql_replica
    login_user: root
    login_password: "{{ mysql_root_password }}"
    query: "SHOW SLAVE STATUS\\G"
  register: replication_status_check
  changed_when: false
  become: yes

- name: Выводим статус репликации
  debug:
    var: replication_status_check.query_result
