- name: Debug installed collections
  run: ansible-galaxy collection list

- name: Установка зависимостей
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
      - python3-pymysql
    state: present
    update_cache: true

- name: Запуск Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Создание рабочей директории
  ansible.builtin.file:
    path: /opt/wordpress
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
