- name: Очистка предыдущих контейнеров и томов
  become: yes
  shell: |
    docker-compose down -v || true
    docker rm -f mysql_master || true
    docker volume rm -f wordpress_mysql_master_data || true
    rm -rf /opt/wordpress/config/*
  args:
    chdir: /opt/wordpress

- name: Установка зависимостей
  apt:
    name:
      - docker.io
      - docker-compose
      - python3-pymysql
    state: present
    update_cache: yes

- name: Запуск Docker
  service:
    name: docker
    state: started
    enabled: yes

- name: Создание рабочей директории
  file:
    path: /opt/wordpress
    state: directory
    mode: 0755
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"