- name: Установка Docker и docker-compose
  apt:
    name: [ docker.io, docker-compose ]
    state: present
    update_cache: true

- name: Копирование docker-compose файла
  copy:
    src: ../docker-compose.yml
    dest: /home/ubuntu/docker-compose.yml

- name: Запуск docker-compose
  command: docker-compose up -d
  args:
    chdir: /home/ubuntu