version: '3.8'

services:
  db-master:
    image: mysql:5.7
    container_name: db-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: wordpress
    volumes:
      - db_master_data:/var/lib/mysql  # Здесь сохраняются данные MySQL-мастера
    ports:
      - "3306:3306"
    networks:
      - wpnet

  db-replica:
    image: mysql:5.7
    container_name: db-replica
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_replica_data:/var/lib/mysql  # Здесь сохраняются данные MySQL-реплики
    networks:
      - wpnet
    depends_on:
      - db-master

  wordpress:
    image: wordpress:latest
    container_name: wordpress
    restart: always
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db-master:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpass
    volumes:
      - wordpress_data:/var/www/html  # Здесь сохраняются данные WordPress: плагины, темы, media и т.д.
    networks:
      - wpnet
    depends_on:
      - db-master

volumes:
  db_master_data:    # Именованный том для хранения данных основного MySQL
  db_replica_data:   # Именованный том для хранения данных реплики MySQL
  wordpress_data:    # Именованный том для хранения данных сайта WordPress

networks:
  wpnet:             # Общая сеть для взаимодействия всех контейнеров