- hosts: wordpress  # Укажите группу хостов из инвентарного файла
  become: yes  # Если необходимо использовать sudo
  tasks:
    - name: Установка Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"  # Установка Docker для Debian/Ubuntu

    - name: Установка Docker Compose
      apt:
        name: docker-compose
        state: present
      when: ansible_os_family == "Debian"  # Установка Docker Compose для Debian/Ubuntu

  roles:
    - mysql
    - wordpress
    - mysql_replica
