name: Deploy WordPress with Ansible

on:
  push:
    branches:
      - DZ2

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      HOST: ${{ secrets.REMOTE_HOST }}
      SSH_USER: ${{ secrets.REMOTE_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Prepare inventory file
        run: |
          echo "[wordpress]" > ansible/inventory.ini
          echo "$HOST ansible_user=$SSH_USER ansible_ssh_private_key_file=~/.ssh/id_rsa" >> ansible/inventory.ini

      - name: Run Ansible playbook
        run: ansible-playbook -i ansible/inventory.ini ansible/setup.yml